#!/usr/bin/env -S bash -euo pipefail

FAMILY=${FAMILY:-${1:?missing family}}
TABLE=${TABLE:-${2:?missing table}}
SETNAME=${SETNAME:-${3:?missing setname}}

mcannounce \
    | jq --unbuffered --seq --raw-output '"\(.op) \(.server) \(.port)"' \
    | while read op server port; do \
        if ! ip -j -4 addr show | jq --exit-status '[.[].addr_info[].local] | any(. == $ip)' --arg ip $server >/dev/null; then
            continue
        fi

        echo "handle $op: $server:$port"

        case $op in
            add) nft add element $FAMILY $TABLE $SETNAME \{ $port \} ;;
            del) nft delete element $FAMILY $TABLE $SETNAME \{ $port \} ;;
        esac
    done
